[project]
name = "probeset-design-pipeline"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.86",
    "gtfparse",
    "numpy>=1.26.4",
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
    "pyensembl>=2.3.13",
    "scipy>=1.17.0",
    "tqdm>=4.67.1",
]

# Needed to support recent python versions
[tool.uv.sources]
gtfparse = { git = "https://github.com/openvax/gtfparse" }

